# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglC <- function(W, C, P_Yosc, P_Xosc, B_T, Dat, sigX, sigY, sigH, sigT, sigTo, sigUo, c1 = 0, c2 = 0, c3 = 0) {
    .Call('PPLS_loglC', PACKAGE = 'PPLS', W, C, P_Yosc, P_Xosc, B_T, Dat, sigX, sigY, sigH, sigT, sigTo, sigUo, c1, c2, c3)
}

EMstepC <- function(W, C, P_Yosc, P_Xosc, B_T, Dat, sigX, sigY, sigH, sigT, sigTo, sigUo, invS = matrixXd::Zero(1,1)) {
    .Call('PPLS_EMstepC', PACKAGE = 'PPLS', W, C, P_Yosc, P_Xosc, B_T, Dat, sigX, sigY, sigH, sigT, sigTo, sigUo, invS)
}

#' Simulate data from a PO2PLS model
#'
#' @param N integer. Sample size
#' @param W numeric matrix. Joint X-loadings, should be an orthogonal matrix with orthonormal columns.
#' @param C numeric matrix. Joint Y-loadings, should be an orthogonal matrix with orthonormal columns.
#' @param P_Yosc numeric matrix. Orthogonal X-loadings, should be an orthogonal matrix with orthonormal columns.
#' @param P_Xosc numeric matrix. Orthogonal X-loadings, should be an orthogonal matrix with orthonormal columns.
#' @param B_T Diagonal matrix. Inner relation parameter
#' @param sigX double. Positive variance parameter for the noise in X
#' @param sigY double. Positive variance parameter for the noise in Y
#' @param sigH double. Positive variance parameter for the noise in U
#' @param sigT Diagonal matrix. Contains positive variances for each latent variable in T
#' @param sigTo Diagonal matrix. Contains positive variances for each latent variable in T_Yosc
#' @param sigUo Diagonal matrix. Contains positive variances for each latent variable in U_Xosc
#' @return Dat. Matrix of size N times p+q. Rows are samples, columns are realisations of X and Y concatenated together.
#' @export
simulC <- function(N, W, C, P_Yosc, P_Xosc, B_T, sigX, sigY, sigH, sigT, sigTo, sigUo) {
    .Call('PPLS_simulC', PACKAGE = 'PPLS', N, W, C, P_Yosc, P_Xosc, B_T, sigX, sigY, sigH, sigT, sigTo, sigUo)
}

loglC_fast <- function(W, C, X, Y, sigX, sigY, sig2T, c1, c2, c3, Kc) {
    .Call('PPLS_loglC_fast', PACKAGE = 'PPLS', W, C, X, Y, sigX, sigY, sig2T, c1, c2, c3, Kc)
}

EMstepC_fast <- function(W, C, B, X, Y, sigX, sigY, sigH, sigT, c1, c2, c3) {
    .Call('PPLS_EMstepC_fast', PACKAGE = 'PPLS', W, C, B, X, Y, sigX, sigY, sigH, sigT, c1, c2, c3)
}

meta_Estep <- function(W, C, B, X, Y, sigX, sigY, sigH, sigT, c1, c2, c3) {
    .Call('PPLS_meta_Estep', PACKAGE = 'PPLS', W, C, B, X, Y, sigX, sigY, sigH, sigT, c1, c2, c3)
}

meta_Mstep <- function(ret) {
    .Call('PPLS_meta_Mstep', PACKAGE = 'PPLS', ret)
}

