# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title here
#'
#' @param X Numeric matrix.
#' @return ...
loglC <- function(W, C, P_Yosc, P_Xosc, B_T, Dat, sigX, sigY, sigH, sigT, sigTo, sigUo, c1 = 0, c2 = 0, c3 = 0) {
    .Call('PPLS_loglC', PACKAGE = 'PPLS', W, C, P_Yosc, P_Xosc, B_T, Dat, sigX, sigY, sigH, sigT, sigTo, sigUo, c1, c2, c3)
}

#' Title here
#'
#' @param X Numeric matrix.
#' @return ...
EMstepC <- function(W, C, P_Yosc, P_Xosc, B_T, Dat, sigX, sigY, sigH, sigT, sigTo, sigUo, invS = matrixXd::Zero(1,1)) {
    .Call('PPLS_EMstepC', PACKAGE = 'PPLS', W, C, P_Yosc, P_Xosc, B_T, Dat, sigX, sigY, sigH, sigT, sigTo, sigUo, invS)
}

#' Title here
#'
#' @param X Numeric matrix.
#' @return ...
simulC <- function(N, W, C, P_Yosc, P_Xosc, B_T, sigX, sigY, sigH, sigT, sigTo, sigUo) {
    .Call('PPLS_simulC', PACKAGE = 'PPLS', N, W, C, P_Yosc, P_Xosc, B_T, sigX, sigY, sigH, sigT, sigTo, sigUo)
}

#' Title here
#'
#' @param X Numeric matrix.
#' @return ...
loglC_fast <- function(W, C, X, Y, sigX, sigY, sig2T, c1, c2, c3, Kc) {
    .Call('PPLS_loglC_fast', PACKAGE = 'PPLS', W, C, X, Y, sigX, sigY, sig2T, c1, c2, c3, Kc)
}

#' Title here
#'
#' @param X Numeric matrix.
#' @return ...
EMstepC_fast <- function(W, C, B, X, Y, sigX, sigY, sigH, sigT, c1, c2, c3) {
    .Call('PPLS_EMstepC_fast', PACKAGE = 'PPLS', W, C, B, X, Y, sigX, sigY, sigH, sigT, c1, c2, c3)
}

